### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by shambhaviparashar** [guotong1988/NL2SQL-RULE#15]
NL2SQL-RULE>python train.py
BERT-type: uncased_L-12_H-768_A-12
Batch_size = 8
BERT parameters:
learning rate: 1e-05
Fine-tune BERT: True
vocab size: 30522
hidden_size: 768
num_hidden_layer: 12
num_attention_heads: 12
hidden_act: gelu
intermediate_size: 3072
hidden_dropout_prob: 0.1
attention_probs_dropout_prob: 0.1
max_position_embeddings: 512
type_vocab_size: 2
initializer_range: 0.02
Load pre-trained parameters.
Seq-to-SQL: the number of final BERT layers to be used: 2
Seq-to-SQL: the size of hidden dimension = 100
Seq-to-SQL: LSTM encoding layer size = 2
Seq-to-SQL: dropout rate = 0.3
Seq-to-SQL: learning rate = 0.001
Traceback (most recent call last):
  File "train.py", line 726, in <module>
    dset_name="train")
  File "train.py", line 221, in train
    for iB, t in enumerate(train_loader):
  File "C:\Users...\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users...\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "C:\Users...\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users...\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users...\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users...\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users...\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_loader_wikisql.<locals>.<lambda>'

...NL2SQL-RULE>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users...\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users...\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by guotong1988** [comment]
It seems there is something wrong with your data input.

**Comment by guotong1988** [comment]
Could you please format your post?

**Comment by guotong1988** [comment]
It seems it is the problem of windows-OS.

**Comment by charlesantoinecaswil** [comment]
I had the same problem, did you solve it ?

**Comment by akashrawatds** [comment]
If you're on a windows machine then you need to modify the get_loader_wikisql() function.

* Make num_workers=0
* Instead of using lambda function in collate_fn define a function inside get_loader_wikisql() and put the function name as value to collate_fn.
---> def identify(x): return x
---> collate_fn=identify

This worked for me.
